version: 6.0.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.ico
navbar:
    menu:
        首页: /
        归档: /archives
        关于: /about
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/zeroshiro
search:
    type: insight
article:
    highlight:
        update_time: true
        theme: atom-one-dark
        clipboard: true
    readtime: true
    license:
        enable: true
        license: CC BY-NC-SA 4.0
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        type: profile
        position: left
        author: ZeroShiro
        author_title: 普通的开发者 / 热情的学习者
        location: China
        avatar: https://avatars.githubusercontent.com/u/48169665?v=4
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/zeroshiro
            # RSS:
            #     icon: fas fa-rss
            #     url: /atom.xml
            Email:
                icon: fas fa-envelope
                url: mailto:1311588796@qq.com
    -
        type: categories
        position: left
        layout: list
    -
        type: recent_posts
        position: right
    -
        type: archives
        position: right
    -
        type: tags
        position: right
footer:
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
        Email Me:
            icon: fas fa-envelope  
            url: mailto:1311588796@qq.com
